site_name: singlepatient
site_description: thoughts and pursuits
site_url: http://singlepatient.github.io

theme:
  name: material
  features:
    - navigation.indexes
  palette:
    scheme: slate
    primary: black


plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories_allowed:
        - thoughts
        - project
        - notes
      authors_profiles: true
      pagination_per_page: 5
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
      post_slugify: !!python/object/apply:ext.slugs.slugify
        kwds:
          short: true
  - meta
  - tags
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

# extra:
#   social:
#     - icon: fontawesome/brands/mastodon
#       name: squidfunk on Mastodon
#       link: https://fosstodon.org/@squidfunk

# hooks:
#   - hooks/socialmedia.py

markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - 2D Art: 2d_art.md
  - 3D Art: 3d_art.md
  - Design: design.md
  - Sketches: sketches.md
  - Home Cooking: cooking.md
  - Blog:
     - blog/index.md
     - blog/tags.md